Auto-reveal
NucleoidMC/Withersweeper pull request #4
Opened 2020-08-16 16:24 UTC by arthurbambou

2020-08-16 16:53 UTC, haykam821 requested changes

2020-08-16 16:53 UTC, haykam821 commented on src/main/java/io/github/haykam821/withersweeper/game/phase/WithersweeperActivePhase.java
> +		if (clickedField.getBlockState() == Blocks.WHITE_WOOL.getDefaultState()) {
Check if this is a number field with the value `0` rather than checking the world representation.

2020-08-16 16:53 UTC, haykam821 commented on src/main/java/io/github/haykam821/withersweeper/game/phase/WithersweeperActivePhase.java
> +	private void autoReveal(ServerPlayerEntity uncoverer, BlockPos clickedBlockPos, Field clickedField) {
```suggestion
	private void uncoverNeighbors(ServerPlayerEntity uncoverer, BlockPos clickedBlockPos, Field clickedField) {
```

2020-08-16 16:53 UTC, haykam821 commented on src/main/java/io/github/haykam821/withersweeper/game/phase/WithersweeperActivePhase.java
> +						if (field.getBlockState() == Blocks.WHITE_WOOL.getDefaultState()) blockPosToCheck.add(blockPos);
Same thing here, check whether this is a number field with the value `0`.

2020-08-16 16:53 UTC, haykam821 commented on src/main/java/io/github/haykam821/withersweeper/game/phase/WithersweeperActivePhase.java
> +				blockPosToCheck.remove(blockPosToCheck.get(0));
Just specify the index here:

```suggestion
				blockPosToCheck.remove(0);
```

2020-08-16 16:53 UTC, haykam821 commented on src/main/java/io/github/haykam821/withersweeper/game/phase/WithersweeperActivePhase.java
> +			this.autoReveal(uncoverer, pos, field);
```suggestion
			this.uncoverNeighbors(uncoverer, pos, field);
```

2020-08-16 16:53 UTC, haykam821 commented on src/main/java/io/github/haykam821/withersweeper/game/phase/WithersweeperActivePhase.java
> +						BlockPos blockPos = new BlockPos(blockPosToCheck.get(0).getX() + x, blockPosToCheck.get(0).getY(), blockPosToCheck.get(0).getZ() + z);
```suggestion
						BlockPos checkPos = blockPosToCheck.get(0);
						if (checkedBlockPos.contains(checkPos)) continue;

						BlockPos blockPos = checkPos.offset(x, 0, z);
```

2020-08-16 16:53 UTC, haykam821 commented on src/main/java/io/github/haykam821/withersweeper/game/phase/WithersweeperActivePhase.java
> +						BlockPos blockPos = new BlockPos(blockPosToCheck.get(0).getX() + x, blockPosToCheck.get(0).getY(), blockPosToCheck.get(0).getZ() + z);
This variable should be named `pos`.

2020-08-16 17:20 UTC, haykam821 requested changes

2020-08-16 17:20 UTC, haykam821 commented on src/main/java/io/github/haykam821/withersweeper/game/phase/WithersweeperActivePhase.java
> +			if (((NumberField)clickedField).getValue() == 0) {
```suggestion
			if (((NumberField) clickedField).getValue() == 0) {
```

2020-08-16 17:20 UTC, haykam821 commented on src/main/java/io/github/haykam821/withersweeper/game/phase/WithersweeperActivePhase.java
> +			if (((NumberField)clickedField).getValue() == 0) {
I'd recommend either two if-statements with early returns or a combined if-statement here.

2020-08-16 17:20 UTC, haykam821 commented on src/main/java/io/github/haykam821/withersweeper/game/phase/WithersweeperActivePhase.java
> +							if (field instanceof  NumberField) {
```suggestion
							if (field instanceof NumberField) {
```

2020-08-16 17:20 UTC, haykam821 commented on src/main/java/io/github/haykam821/withersweeper/game/phase/WithersweeperActivePhase.java
> +								if (((NumberField)field).getValue() == 0)
```suggestion
								if (((NumberField) field).getValue() == 0)
```

2020-08-16 17:20 UTC, haykam821 commented on src/main/java/io/github/haykam821/withersweeper/game/phase/WithersweeperActivePhase.java
> +								if (((NumberField)field).getValue() == 0)
These should be combined into a single if-statement.

2020-08-16 17:20 UTC, haykam821 commented on src/main/java/io/github/haykam821/withersweeper/game/phase/WithersweeperActivePhase.java
> +							if (checkedBlockPos.contains(checkPos)) continue;
Add an empty line after this line too.

2020-08-16 17:20 UTC, haykam821 commented on src/main/java/io/github/haykam821/withersweeper/game/phase/WithersweeperActivePhase.java
> +							}
Add an empty line after this line as well.

2020-08-16 17:20 UTC, haykam821 commented on src/main/java/io/github/haykam821/withersweeper/game/phase/WithersweeperActivePhase.java
> +				blockPosToCheck.add(clickedBlockPos);
Add an empty line after this line.

2020-08-16 17:20 UTC, haykam821 commented on src/main/java/io/github/haykam821/withersweeper/game/field/NumberField.java
> +		return value;
```suggestion
		return this.value;
```

2020-08-16 17:20 UTC, haykam821 commented on src/main/java/io/github/haykam821/withersweeper/game/phase/WithersweeperActivePhase.java
> +				List<BlockPos> blockPosToCheck = new ArrayList<>();
This variable should be named `uncheckedPositions`.

2020-08-16 17:20 UTC, haykam821 commented on src/main/java/io/github/haykam821/withersweeper/game/phase/WithersweeperActivePhase.java
> +				List<BlockPos> checkedBlockPos = new ArrayList<>();
This variable should be named `checkedPositions`.

2020-08-16 17:20 UTC, haykam821 commented on src/main/java/io/github/haykam821/withersweeper/game/phase/WithersweeperActivePhase.java
> +								this.modifyField(uncoverer, pos, field);
```suggestion
							if (field.getVisibility() == FieldVisibility.COVERED) {
								this.modifyField(uncoverer, pos, field);
							}
```

2020-08-16 17:20 UTC, haykam821 commented on src/main/java/io/github/haykam821/withersweeper/game/phase/WithersweeperActivePhase.java
> +					checkedBlockPos.add(blockPosToCheck.get(0));
```suggestion
					checkedBlockPos.add(checkPos);
```

2020-08-16 21:36 UTC, arthurbambou commented
I made it optional.

2020-11-24 16:56 UTC, arthurbambou commented
I think I've fixed everything you asked me to change. Can you review it again (please)?

2021-01-21 16:02 UTC, closed without merging